# Generated by Django 5.1.2 on 2024-10-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('Id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=100)),
                ('Genero', models.CharField(max_length=20)),
                ('Plataforma', models.CharField(max_length=30)),
                ('Fecha_lanzamiento', models.DateField()),
                ('Stock', models.IntegerField()),
            ],
        ),
    ]
